# syntax=docker/dockerfile:1
FROM golang:1.26 AS builder

WORKDIR /build
COPY go.mod ./
COPY cmd ./cmd
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-w -s" -o /build/auth-broker ./cmd/broker

FROM scratch
COPY --from=builder --chown=0:0 /build/auth-broker /auth-broker
USER 0:0
WORKDIR /data
EXPOSE 8080
ENTRYPOINT ["/auth-broker"]
